name: PatrCloud
on: 
  workflow_dispatch:
jobs:
  main:
    name: Checkout this Repo,Build on Docker,then Push it to Patr
    runs-on: ubuntu-latest
    steps: 
    - name: SetUpDockerEnv
      uses: crazy-max/ghaction-setup-docker@v1.1.0
    - name: Checkout
      uses: actions/checkout@v2.7.0
    - name: Build,Login,Push
      run: |
        docker login registry.patr.cloud -u ${{ secrets.USER }} -p ${{ secrets.TOKEN }}
        docker build . -t registry.patr.cloud/6a57ffe37679493b9497ccdad368e83c/dendrite
        docker push registry.patr.cloud/6a57ffe37679493b9497ccdad368e83c/dendrite
